### ISSUE TITLE
Exceptions in WSSE nonce cache under heavy load

### ISSUE THREAD

**Issue by ramunasd** [oroinc/platform#314]
Looks like nonce cache purge function tries to remove already removed cache items.
Caching to files isn't very good choice :) Maybe we could use dedicated SQlite3 or common cache storage?

Version: 1.7.2
`
file: .../vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Cache/WsseNoncePhpFileCache.php | ctxt_exception: {"class":"RuntimeException","message":"SplFileInfo::getMTime(): stat failed for .../app/cache/prod/security/nonces/6/[NjUxNzMwRUEzRDVCRTJDNzkzNzg2ZGFjY2FiNy04MjE0LTQ0NjEtOGMwZC02MTZhZjRhNmZhMjA=][1].doctrinecache.php","file":".../vendor/oro/platform/src/Oro/Bundle/SecurityBundle/Cache/WsseNoncePhpFileCache.php:171
`

**Comment by stalxed** [comment]
+1 I have this warnings too.

**Comment by artml** [comment]
That should have been fixed within 1.9 release; @ramunasd @stalxed can you please check if it's still relevant? Thank you.

**Comment by ramunasd** [comment]
Hi @artml, from what i see this issue remains. It's bad practice to do purging before every write to cache. This leads to bad performance and missing file issues.

**Comment by adamlundrigan** [comment]
I am seeing this in my prod env running 1.10.2.  Two small clusters appeared in the logs and both coincide with periods of heavy API traffic (batch process running against API)

**Comment by artml** [comment]
Thank you for the feedback. We are going to give this topic a priority in the coming months.

**Comment by sergeyz** [comment]
> Maybe we could use dedicated SQlite3 or common cache storage?

Common storage if file storage now. I'm not sure it will be good option to require sqlite or redis from platform package.

You can set nonce_cache_service_id parameter https://github.com/djoos/EscapeWSSEAuthenticationBundle#specify-a-custom-nonce-cache-default-doctrinecommoncachephpfilecache-in-kernelcache_dirsecuritynonces and configure service to use sqlite or redis in your application's config.yml

Here is example how to add new cache service https://github.com/orocrm/redis-config/blob/master/Resources/config/services.yml#L53-L57

**Comment by sadortun** [comment]
@artml  This issue is still present in 2.1.x  With around 50 API requests / second.

**Comment by sadortun** [comment]
@adamlundrigan Did you solve your issue ?

**Comment by sadortun** [comment]
My feeling about this is that under heavy load,  the cache purge interval is in SECONDS. so, when the cache is actually purged,  later `nonce` from the same second are purged.

https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/Cache/WsseNoncePhpFileCache.php#L115

A few possible solutions:
- use  `microtime(true)` instead of `time()`
- Purge only previous range (a.k.a.  substract one second) 
`if ($startTime - $lastPurgeTime - 1 < self::PURGE_INTERVAL)`

**Comment by adamlundrigan** [comment]
@sadortun we do still see it periodically, but ignore it.  Your feeling on the cause fits with what we've seen...the problem only really shows up when sending API requests rapidly (eg: API client bulk-importing some records), which makes sense since under light load there may not be an API request in the fraction of a second between nonce purge and rollover to the next integer second.

**Comment by sadortun** [comment]
@adamlundrigan Thanks for the update. If you have any chance, when you got theses errors, you can try to comment out (**temporarly**) 
https://github.com/orocrm/platform/blob/master/src/Oro/Bundle/SecurityBundle/Cache/WsseNoncePhpFileCache.php#L116

And see if the errors stops.

**Comment by anyt** [comment]
Fixed in 3.1.10. Thank you for your contribution!
