### ISSUE TITLE
Grids: The grid doesn't display when user reduces browser window

### ISSUE THREAD

**Issue by alex-mak** [oroinc/platform#745]
Issue is reproducing on demo
![2017-08-29_1225](https://user-images.githubusercontent.com/6999236/29814929-aa04aa74-8cb7-11e7-9c5d-d9d516f4d1e1.png)

![2017-08-29_12h31_32](https://user-images.githubusercontent.com/6999236/29815425-3decb3e8-8cb9-11e7-9e81-cd69a550b70b.gif)

**Comment by alex-mak** [comment]
Hi guys,

The issue was found on IE 11.0.9600.18762, however, you can see from the video attached that it can be reproduced on Chrome (and also on all browsers).
Steps to reproduce:
1. Go to Users grid (or any other with some amout of rows)
2. Maximize -> Restore Down -> Maximize -> Restore Down -> Maximize -> Restore Down -> Maximize -> Restore Down -> Maximize -> Restore Down. etc. 
And the issue comes..

**Comment by manowark** [comment]
Hello, @alex-mak.

We will try to reproduce that bug (because this bug not trivial) and fix it in short time.

Internal ID: BAP-15375

**Comment by rudenskij** [comment]
Hi **@alex-mak**.,

We have investigated the issue taking into account described environment and your steps to reproduce. Seems like it has been fixed and cannot be reproduced on the latest version of our applications.

Thank you and have a nice day.

**Comment by jneto81** [comment]
The problem still exists in demo.orocrm.com.
I'm using Chromium in linux.

**Comment by mbessolov** [comment]
Confirmed in Chromium/Linux - when resizing the browser window the grid is constantly being re-drawn, and on some browser window dimensions it disappears completely.

**Comment by anyt** [comment]
Cannot reproduce the issue on the latest master in IE 11 and Chrome. Seems like it has been fixed or has additional conditions. In any case, the bug is not relevant anymore.

Thank you for contribution!
